### PR TITLE
mounting licence and database config outside of volume - non persistent

### PR DESCRIPTION
**Pull request by mastnym**
When you want to change license (and possibly db config) you need to delete whole persistent cxn_volume. After this change, both files are mounted as non persistent, so you can switch license only by swapping files on host and the rest of the files in volume is kept.

### CODE REVIEW

**Comment by bzaicsek-cxn** [comment]
Hi!

   This change can be real useful for someone who uses JChem Webservices in docker in production but keeping it in mind that this is only an example for people who has trouble to set it up by themselves and this feature (linking file directly from host machine) is problematic on windows, I would not change the example. However I have added it as a solution in an alternative compose file.

Regards:
Balázs

**Comment by mastnym** [comment]
Thanks for considering this, in fact, I'm running this on Windows 10 machine and everything works as expected. The fact is that the inexperienced user could be lost, because new license does not appear in the container even if it is copied to the folder on host computer.

**Comment by bzaicsek-cxn** [comment]
I am  running it with Windows 10 pro, and Docker 2.1.0.5 (40693) and I've got an error for trying out your solution. On linux it has worked fine.

**Comment by mastnym** [comment]
What kind of error are you getting? I have the exact same setup. When I first tried `docker-compose up` I got some weird error about existing file, but from then everything is fine

**Pull request closed without merging**
